### ISSUE TITLE
Error: No such filter: '' Error initializing complex filters. Invalid argument

### ISSUE THREAD

**Issue by ullenboom** [pilotpirxie/json-to-ffmpeg#2]
I am using your JSON in a simple program:

```
import { parseSchema } from 'json-to-ffmpeg';
import * as fs from 'fs';

const schema = {
  "version": 1,
  "inputs": {
...
    "endPosition": 38,
    "scaleRatio": 0.2
  }
};


const ffmpegCommand = parseSchema(schema);
fs.writeFileSync("command.sh", ffmpegCommand);
```

Also using your example files in the sample folder.

Executing command.sh leads to:

```
[AVFilterGraph @ 0x5653cb3d52c0] No such filter: ''
Error initializing complex filters.
Invalid argument
```

output.mp4 is 257 KiB and invalid.

**Comment by pilotpirxie** [comment]
Hi @ullenboom can you please provide the full schema you are using?

**Comment by ullenboom** [comment]
I copied the JSON from your README. First movies got generated, but the joining in the end fails.
I am using Debian in WSH with a fresh installation of FFmpeg.

[index.mjs.txt](https://github.com/user-attachments/files/16086405/index.mjs.txt)

**Comment by pilotpirxie** [comment]
Can you please post command.sh? If you use the README example, it should work with the default distribution of FFmpeg. 
Maybe it has something to shell script format, ``"`` and ``'`` in your operating system.
https://stackoverflow.com/questions/69128505/ffmpeg-no-such-filter-error-initializing-complex-filters
https://stackoverflow.com/questions/65291525/no-such-filter-error-initializing-complex-filters-invalid-argument
https://superuser.com/questions/1770042/error-initializing-complex-filters-no-such-filter-in-ffmpeg

**Comment by pilotpirxie** [comment]
Stale, closing
